### ISSUE TITLE
如何做这个BP?

### ISSUE THREAD

**Issue by WangYuBo** [billbamboo/team-of-fortuneteller#5]
几个切入点:
1. 整清楚占卜的过去/现在与未来;
猜测:(本质是人对未来预期,降低不确定性);所以,只要有对未来预期有不确定性存在,占卜就会存在;

2. 从古到今,商业方式变化;

3. 参考IA BP指南;

**Comment by billbamboo** [comment]
15页ppt | 内容的TIPS:时间空间变量关系、有趣+套利
-- | --
1 | 路演目录：网络算命的全局认识（时间空间变量关系）、网络算命、结论与洞察
2 | 网络算命的起源 1：算命的起源；网络算命的起源
3 | 时间：网络算命的发展趋势（兴起的形式——功能机——智能机——AI和大数据）
4 | 空间：全球集中在亚洲（待验证），中国集中在哪几个省市
5 | 空间：市场集中度很低
6 | 变量：模因（星座、周易、风水、面相、手相）
7 | 变量：人群性格（文献和app运营内容得出）
8 | 变量：经济发展（经济发展与算命的兴起是反相关，行业不确定性越大越相信）
9 | 从知名上市公司说起-Zapp（一个上市公司的分析）
10 | 社区-龙隐社区
11 | 资本青睐什么：风投20家（几个公司的分析）
12 | 结论与洞察：盈利模式
13 | 结论与洞察：战略指数
14 | 赢利点：不是算命的相关的  网易的小游戏
15 | 网络算命的未来：天然付费属性、人工智能与大数据结合

**Comment by WangYuBo** [comment]
1. 发现现象： 科学昌明，还有算命公司上市，大陆还有很多拿到了风投．
2. 问题：为什么义务教育普及，还有这么多人算命／星盘？日本还有算命公司为什么能上市？
3. 假设：
     1.　算命求心安
     2.　减少信息熵；

4. 分析数据：

5. 得出结论：

6. 寻找到的套利方案：
