### ISSUE TITLE
算命vs星座:文化产业or科技产业?我们似乎只能选一个深入．

### ISSUE THREAD

**Issue by WangYuBo** [billbamboo/team-of-fortuneteller#7]
同道大叔等星盘很明显是文化产业范畴，围绕IP开发走；
有些是服务行业，聚集大量风水老师，做在线服务的；

前者围绕模因，后者技因主导．

以目前时间精力看，似乎只能深入一个方向．

**Comment by iyangming00** [comment]
还需要再抽象，我们分析的维度高度不够的。

**Comment by WangYuBo** [comment]
分析ai技术＋算命属性较强的神棍局.
