### ISSUE TITLE
建立算命行业最小全局认识，而不是大而全的认识．

### ISSUE THREAD

**Issue by WangYuBo** [billbamboo/team-of-fortuneteller#8]
觉着咱们是不是分析的有点多和杂了／？

**Comment by billbamboo** [comment]
刚开始不了解的时候，必然搜索范围会变大变散，因为没有找到更精准的维度去形成最小全局。
我们可以扩展到算命行业最小全局认识是模因（各种算命方法）+模因的传播+模因的套利
从优雅的套利出发，我觉得有几个点：
1 如何选择和传播模因（哪些适合线上套利，哪些不适合）
2 如何选择避开套利的风险点
3 如何找到优雅套利的核心因素（群众的力量=开源库，技术结合）

**Comment by WangYuBo** [comment]
回答上面三个问题：
1 如何选择和传播模因（哪些适合线上套利，哪些不适合）
需要调查数据支持，也需要预测未来趋势．
猜测星座／八字等在婚恋／事业等领域适合；

2 如何选择避开套利的风险点；
政策风险：注册有限责任公司，鸡蛋放几个篮子里．

3 如何找到优雅套利的核心因素（群众的力量=开源库，技术结合）
