### ISSUE TITLE
关于套利的思考框架

### ISSUE THREAD

**Issue by iyangming00** [billbamboo/team-of-fortuneteller#9]
整个bp重点在于如何找到套利机会，我们需要找到一个思考框架可以用来分析我们面对的机会。我觉得这个思考框架应该具备以下几个特征：

1.  空间维度：可以复用到更多的行业内。比如可以用来在知识付费，新媒体行业找到套利机会。
2. 时间维度： 过去已经发生，将来会发生。文化行业或知识付费行业发生的事情，网络算命也会发生。
3. 成本维度：成本最小。这里包含金钱成本，精力成本等。

**Comment by WangYuBo** [comment]
1. 一个直观的网络算命套利机会，是利用github中开源算命／星盘算法，直接建成网站／小程序；这个方法成本最低，最省精力；
2. 空间维度：上述方法能覆盖到所有占卜性质的领域；
3. 时间维度：只是一时趋势，将来必然算命是AI＋大数据．

**Comment by billbamboo** [comment]
1.如果是一个直观的网络算命的套利机会的话，是不是一个开源的库?
2.变量关系：为了规避风险，是不是可以改变模因，或者模糊
3.时间维度：紧跟着技术趋势

**Comment by WangYuBo** [comment]
空间维度还可以让八字走英语系国家，把八字程序／网站放fb,twitter等等．
